name: Package and sign

on: [push]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write

    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.14
      # discover the newly created conda file in the output directory
      # - name: Find conda package
      #   id: find
      #   run: |
      #     echo "::set-output name=conda_file::$(find output/ -name '*.conda')"
      - uses: actions/attest@v1
        id: attest
        with:
          subject-path: "**/*.conda"
          predicate-type: "https://example.com/predicate/v1"
          predicate: "{}"

      - name: Get JWT
        id: get_token
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken('prefix.dev')
            core.setOutput('token', token)

      - name: Mint the API Key on prefix.dev
        run: |
          TOKEN="${{ steps.get_token.outputs.token }}"
          RESPONSE=$(curl -s -X POST                      \
              https://preview-lenient-marlin.prefix.dev/api/oidc/mint_token \
              -H "Content-Type: application/json"        \
              --data "{\"token\": \"$TOKEN\"}")
          # mask the response
          echo "::add-mask::$RESPONSE"
          echo "PREFIX_API_KEY=$RESPONSE" >> $GITHUB_ENV
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install requests
        run: |
          pip install requests

      - name: Use the API Key
        run: |
          export BUNDLE_PATH=${{ steps.attest.outputs.bundle-path }}
          python ./upload_multipart.py