name: Package and sign

on: [push]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write

    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rattler-build
        run: |
          curl -L https://github.com/prefix-dev/rattler-build/releases/download/v0.45.0/rattler-build-x86_64-unknown-linux-musl -o rattler-build
          chmod +x rattler-build
          sudo mv rattler-build /usr/local/bin/rattler-build
      - name: Build the package with rattler-build
        run: |
          rattler-build build --recipe ./conda.recipe
          tree
      - uses: actions/attest@v1
        id: attest
        with:
          subject-path: "**/*.conda"
          predicate-type: "https://schemas.conda.org/attestations-publish-1.schema.json"
          predicate: "{\"targetChannel\": \"https://prefix.dev/wolf-channel\"}"

      - name: Upload the package
        run: |
          ./rattler-build upload prefix -c wolf-private-test ./output/**/*.conda --attestation ${{ steps.attest.outputs.bundle-path }}
